In [1]:
#Importing the numpy library and aliasing it as 'np' to save time
import numpy as np

In [2]:
#Creating a basic one dimensional array and printing out the contents and the shape
myArray = np.array([1,2,3])
print(myArray)
print(myArray.shape)

[1 2 3]
(3,)


In [3]:
#Printing out each individual element of the array by indexing
print(myArray[0], myArray[1], myArray[2])

1 2 3


In [4]:
#Changing an element of the array
myArray[0] = 5
print(myArray)

[5 2 3]


In [8]:
#Creating a two dimensional array and printing out the contents and the shape
twoDimensionalArray = np.array([[1,2,3],
                                [4,5,6]])
print(twoDimensionalArray)
print(twoDimensionalArray.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
#Printing out the first element by indexing using both the row number and column number
print(twoDimensionalArray[0,0])

1


In [11]:
#Arrays are not limited to just integers
floatArray = np.array([1.4, 2.3, 3.6])
print(floatArray)

stringArray = np.array(['hello', 'world'])
print(stringArray)

[1.4 2.3 3.6]
['hello' 'world']


In [17]:
#There are many useful functions for creating arrays

#Creating an array of a specified shape with all zeros
zeroArray = np.zeros((5,5))
print(zeroArray)

#Creating an array of a specified shape with all ones
onesArray = np.ones((2,3))
print(onesArray)

#Creating an array of a specified shape with any constant value
constantArray = np.full((4,4), 'hello')
print(constantArray)

#Creating an array of a specified shape with random numbers between [0, 1)
randArray = np.random.random((3,3))
print(randArray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']]
[[0.97086796 0.87258703 0.90155995]
 [0.95568007 0.30131359 0.30123314]
 [0.63167969 0.25157499 0.67187362]]


In [21]:
#Just like with normal lists in Python, you can also 'slice' your array to cut out pieces you're interested in
twoDimensionalArray = np.array([[1,2,3,4],
                                [5,6,7,8],
                                [9,10,11,12]])
print(twoDimensionalArray)

#Lets say we want the values in the first two rows AND the values in the middle two columns
#Remember, with slicing, the number on the right side of the colon is non-inclusive
alteredArray = twoDimensionalArray[:2, 1:3]
print(alteredArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [26]:
#With numpy arrays, if you use one array to create a new array (Example: your new array is only the first two columns
#of the original), if you modify your new array, it will also modify the original
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)

b = a[:2, 1:3]
print(b)

b[0,0] = 75
print(a)
print(b)

#You can see that both arrays now have 75 even though we only modified 'b'

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[ 1 75  3]
 [ 4  5  6]
 [ 7  8  9]]
[[75  3]
 [ 5  6]]


In [28]:
#We can also return a boolean value if a certain value in your array satisfies a certain condition
a = np.array([[1,2],
              [3,4],
              [5,6]])
print(a)
print(a > 2)

#It returns false if an element is less than 2 and true if it's greater than or equal to

#Boolean indexing can also be used to only return values that satisfy your condition
print(a[a > 2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [38]:
#Math operations are also very easy to compute with numpy arrays
x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])

#Addnig the array element-wise using both the + operator or the np.add() function
print(x + y)
print(np.add(x,y))

#Doing the same with other operators
print(x - y)
print(np.subtract(x,y))

print(x * y)
print(np.multiply(x,y))

print(x / y)
print(np.divide(x,y))

#Finding the sum of all elements in the array
print(np.sum(x))

#Finding the sum of each column
print(np.sum(x, axis=0))

#Fuinding the sum of each row
print(np.sum(x, axis=1))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
10
[4 6]
[3 7]
